(function(){if(!window.console)window.console={log:function(){}};var c=Archmap={};c.log=function(h){try{console.log(h)}catch(i){}};c.components=[];c.uri="";var a=[],b=[];c.initialize=function(h){c.user=new c.User(h.archmap_says.you);var i=new c.DataStore(c.user);c.dataStore=i;i.infuseInline(h.archmap_says,function(){c.mainDataProvider=function(){return i.dataProvider};c.provider=function(){return i.dataProvider.model};$(function(){c.ImageOverlays.listenForImages();d();c.Template.templatize("body");
e();setTimeout(function(){c.interlocute($("div#stage"))},1E3)})})};c.blankCheck=function(){c.user=new c.User({id:1,isUser:10});c.dataStore=new c.DataStore(c.user)};c.beforeReady=function(h){b.push(h)};var d=function(){_.each(b,function(h){h()})};c.whenReady=function(h){a.push(h)};var e=function(){_.each(a,function(h){h()})},f=function(){_(c.components).each(function(h){h.destroy()});c.components=[]};c.update=function(h){c.dataStore.infuseInline(h.archmap_says,function(){c.Template.templatize("div#stage")})};
c.bindModel=function(h,i){c.EditorialBoard.bindModel(h,i)};var g=undefined;$(window).resize(function(){c.resizeWindow()}).unload(function(){f()});c.resizeWindow=function(){clearTimeout(g);g=setTimeout(function(){$("html").trigger("windowResized")},100)};c.triggerEvent=function(h,i){$("html").trigger(h,i)}})();
(function(){var c=Archmap,a={},b={},d={},e={},f=[];c.IO={get:function(g){var h=g.url,i=g.urlParams||{},k=g.callback,j=g.dataType||"json",m=g.shouldCache||false;if(h===undefined)return false;if(typeof k==="function"){if(d[h]===undefined)d[h]=[];d[h].push(k)}if(b[h])c.IO.sendGet(h);else if(a[h]!==true){a[h]=true;i.linkBase=c.uri;this.remoteGrab(h,{url:c.uri+h,dataType:j,data:i,cache:m,success:function(n){b[h]=n;if(j==="json"||j==="html")c.IO.remember(h,n);a[h]=false;j==="json"?c.dataStore.convertJSONToArchObjects(n.archmap_says,
function(o){e[h]=o;c.IO.sendGet(h)}):c.IO.sendGet(h)},complete:function(n){n.status>400&&g.errback&&g.errback()}})}},remoteGrab:function(g,h){$.ajax(h)},remember:function(){},clearRequireQueue:function(){var g=c.uri,h=f;f=[];for(var i=0;i<h.length;i+=1)g+=h[i]+"+";$.ajax({url:g.slice(0,-1),dataType:"script",success:function(){$.each(h,function(k,j){b[j]=true;a[j]=false;c.IO.sendGet(j)})}})},getFresh:function(g,h){b[g]=false;c.IO.get({url:g,callback:h})},sendGet:function(g){var h=d[g],i=h.length;if(h!==
undefined){for(var k=0;k<i;k+=1)c.IO.sendGetCallback(g,h[k]);d[g]=[]}},sendGetCallback:function(g,h){try{h(b[g],e[g])}catch(i){setTimeout(function(){h(b[g],e[g])},500)}},put:function(g,h,i,k){$.ajax({type:"POST",url:c.uri+"/api/"+g+".json?read=true&link_base="+c.uri,data:"_method=PUT&"+h+"="+i,dataType:"json",success:function(j){var m=c.dataStore.convertJSONToArchObjects(j.archmap_says);k(j,m)}})},post:function(g,h,i){$.ajax({type:"POST",url:c.uri+"/api/"+g+".json?read=true",data:h,dataType:"json",
success:function(k){var j=c.dataStore.convertJSONToArchObjects(k.archmap_says);i(k,j)}})},del:function(g,h){$.ajax({type:"POST",url:c.uri+"/api/"+g+".json?read=true",data:{_method:"DELETE"},dataType:"json",success:function(i){h(i)}})},getJSONModel:function(g,h,i,k,j){g="/api/"+g+".json";if(i===true)b[g]=undefined;c.IO.get({url:g,dataType:"json",callback:h,urlParams:k,errback:j})},loadPartial:function(g){$.ajax({url:g,dataType:"html",data:{mode:"partial"},success:function(h){$("div#stage").empty().html(h)}})},
require:function(g,h){if($.isArray(g)){var i=g.length;_(g).each(function(j){this.require(j,function(){i-=1;i===0&&h()})},this)}else{if(g.contains("components")){var k=g.split("/").pop().replace(".js","");if(c[k]!==undefined){h();return}g+="/"+k}if(g.contains("dependencies"))g="script/"+g;c.IO.get({url:"/"+g+".js",dataType:"script",callback:h,shouldCache:g.indexOf("dependencies")>=0})}},getComponentHtml:function(g,h){c.IO.get({url:"/components/"+g+"/"+g+".html",callback:h,dataType:"html"})}};c.State=
{save:function(g){g.type=="Collection"&&c.IO.require("dependencies/Cookies",function(){$.cookie("last_collection",g.key());c.log("last collection set to be "+g.key())})},retrieve:function(){return $.cookie("last_collection")}}})();
(function(){var c=Archmap;c.Template={templatize:function(a){a=$(a);var b=c.dataStore,d=b.dataProvider.model;a.addClass("model_holder").data("model",d);var e=b.dataProvider;a.find(".component").each(function(){var f=$(this),g=f.attr("id");if(g=="")g=f.attr("class").match(/^[A-Z][\w0-9]+\b/)[0];var h=f.attr("rel"),i=function(){var j={sandbox:f},m=f.attr("options");m&&_.each(m.split(";"),function(l){l=l.split(":");j[l[0]]=l[1]});var n=function(l){l=new c[g](l);f.data("thisComponent",l)};if(h==="this"||
h===""||h===undefined){j.provider=e;n(j)}else{var o=function(l){c.dataStore.get(l,function(p){j.provider=p;n(j)})};h.indexOf("cookie")>=0?c.IO.require("dependencies/Cookies",function(){var l=h.split(";");l=$.cookie(l[0].split(":")[1])||l[1].split(":")[1];o(l)}):o(h)}},k=f.attr("loaddefer");if(k=="true")k=1800;k?setTimeout(function(){c.IO.require("components/"+g,i)},k):c.IO.require("components/"+g,i)});a.find(".model_holder").each(function(){$(this).data("model",c.dataStore.get($(this).attr("rel")))});
a.find(".pretty").each(function(){$(this).html($(this).text().replace(/\'/g,"&rsquo;").replace(/\n/g,"<hr/>"))});a.find(".editable.clickable").each(function(){var f=$(this),g=f.text();if(g==""||g.match(/^[\s]+$/)||!g)f.html("<em>n/a</em>")})}}})();
(function(){var c=Archmap;c.User=function(a){this.initialize(a)};c.User.prototype={initialize:function(a){this.data=a;if(this.data.auth_level>1)this.editor=new c.Editor(this.data.auth_level);else{var b=function(){$(".hoverable").removeClass("hoverable");$(".clickable").removeClass("clickable");$(".editable").removeClass("editable")};$("html").bind("HTMLUpdated",b);$(function(){b()})}}};c.EditorialBoard={makeEditable:function(a){a.element.addClass("editable").addClass(a.interaction).attr("rel",a.field);
c.EditorialBoard.bindModel(a.element,a.model)},makeHoverableEditable:function(a){a.interaction="hoverable";c.EditorialBoard.makeEditable(a)},makeClickableEditable:function(a){a.interaction="clickable";c.EditorialBoard.makeEditable(a)},bindModel:function(a,b){a.addClass("model_holder");b instanceof c.Model?a.attr("type",b.key()).data("model",b):c.dataStore.get(b,function(d){a.attr("type",d.key()).data("model",d)})},editableParagraph:function(a,b,d){b=$("<p/>",{html:d,"class":"editable hoverable",rel:b});
this.bindModel(b,a.key());return b}};c.Editor=function(a){this.initialize(a)};c.Editor.prototype={initialize:function(a){this.known_metas={};this.auth_level=a;this.listen()},listen:function(){var a=this;$("body").find(".editable.clickable").live("click",function(){a.clickProcess2($(this));return false});$("body").find(".editable.hoverable").live("mouseover",function(){$(this).find(".edit-hover").length==0&&$(this).append("<a href='#edit' class='edit-hover'>Edit!</a>")});$("body").find(".edit-hover").live("click",
function(){var b=$(this).parent();a.clickProcess(b);return false})},clickProcess2:function(a,b){var d=a.closest(".model_holder").data("model"),e=a.attr("rel"),f=this;c.dataStore.getMetaForModelAndField(d.type,e,function(g){f.isAuthorized2(g)===true&&f.makeEditable2(d,g,a,b)})},clickProcess:function(a){var b=a.closest(".model_holder").data("model"),d=a.attr("rel"),e=this;c.dataStore.getMetaForModelAndField(b.type,d,function(f){e.isAuthorized2(f)&&e.makeEditable(b,f.data,a)})},mapProcess:function(a,
b,d){d.find("strong[rel='lat']");d.find("strong[rel='lng']")},mapProcess2:function(a,b,d){var e=d.find("strong[rel='lat']"),f=d.find("strong[rel='lng']");e.text(a);f.text(b);var g=this;this.clickProcess2(e,function(){g.clickProcess2(f);f.blur()});e.blur()},isAuthorized2:function(a){if(a.get("auth_level")>this.auth_level){alert("You are not authorized to edit this");return false}return true},isAuthorized:function(a){if(a.status=="404"){alert("Hmm... I don't know if you can edit this. Ask Rob about it.");
return false}else if(a.response.Meta.auth_level>this.auth_level){alert("You are not authorized to edit this.");return false}else return true},suggestify:function(){},makeEditable2:function(a,b,d,e){var f=false,g=this,h=$("<div/>",{"class":"editor",html:$("<button/>",{text:"Cancel",click:function(){f=true;d.html(d.data("original"))}})});d.addClass("editing").data("original",d.html()).attr("contentEditable",true).bind("paste",function(){$(this).html();var i=$(this);setTimeout(function(){i.html(g.convertPaste(i))},
0)}).blur(function(){d.unbind("blur");setTimeout(function(){d.removeClass("editing").attr("contentEditable",false).next("div.editor").remove();if(f===false){h.empty().html("<em>Saving....</em>");g.save2(a,b,d,e);h.remove()}},100)}).find("a.edit-hover").remove();d.focus();b.get("type")=="textarea"&&d.after(h)},makeEditable:function(a,b,d){var e=d.clone();e.find("a.edit-hover").remove();e.find("a.inline").each(function(){var k=$(this).text()||$(this).find("img").attr("title")||null,j=$(this).attr("href").replace(c.uri+
"/","").split("/");j="["+c.Config.abbrevs[j[0]]+"-"+j[1]+"]";k?$(this).text("_"+k+"_ "+j):$(this).text(j)});e.find("em.inline").each(function(){$(this).text("*"+$(this).text()+"*")});e.find("span.underlined").each(function(){$(this).text("%%"+$(this).text()+"%%")});var f=e.html().toString();f=f.replace(/<br>/g,"\n");f=this.characterConvert(f);e.html(f);f=e.text();if(f=="unavailable...")f="";var g=d.css("display");d.css("display","none").after("<div class='editor'><button rel='save'>Save</button><button rel='cancel'>Cancel</button></div>");
b.type=="input"?d.next(".editor").prepend("<input class='put' value='"+f+"' type='text'/>"):d.next(".editor").prepend("<textarea class='put'>"+f+"</textarea>");var h=this,i=$(d).next(".editor");i.find("button[rel='save']").click(function(){var k="";k=b.type=="input"||b.type=="textarea"?i.find(".put").attr("value"):i.find(".put").text();h.save(a,b,d,k);$(d).css("display",g);i.remove()});i.find("button[rel='cancel']").click(function(){$(d).css("display",g);i.remove()})},boil:function(a){a=this.characterConvert(a.html().toString());
return a=a.replace(/(<br(\/)?>){2}/g,"\n\n").replace(/&nbsp;/g," ").replace(/(<|&lt;)(\/)?[\w]+(>|&gt;)/g,"").replace(/\n[ ]+/g,"\n")},convertPaste:function(a){return this.characterConvert(a.html().toString().replace(/\n/g," ").replace(/<\/(div|p|h(1|2|3|4|5|6))>/g,"{n}").replace(/<[^<>]+(\/)?>/g," ").replace(/\{n\}/g,"<br/><br/>"))},characterConvert:function(a){a=a.replace(/\u201c/g,'"').replace(/\u201d/g,'"');a=a.replace(/\u2018/g,"'").replace(/\u2019/g,"'");return a=a.replace(/\u2014/g," -- ").replace(/\u2013/g,
"--")},save2:function(a,b,d,e){var f=b.get("field");b=this.boil(d);a.set(f,b,function(){a.getFresh(f,function(g){d.html(g);typeof e==="function"&&e()})})},save:function(a,b,d,e){var f=b.field;e=this.characterConvert(e);a.set(f,e,function(){a.getFresh(f,function(g){d.empty().html(g)})})}};c.PopoverEditor=function(a,b){this.start(a,b)};c.PopoverEditor.prototype={start:function(a,b){this.model=a;this.callback=b;this.dom=$("<div/>",{"class":"popover"});$("body").append(this.dom);var d=this;c.IO.getComponentHtml("PopoverEditor",
function(e){d.dom.append(e);d.listen();d.dom.children("div").append("<h3>More Information</h3>");d.loadAllEditableFields(d.model);c.EditorialBoard.bindModel(d.dom.children("div"),a.key());d.dom.height($(document).height());d.dom.find(".popover_panel").css("marginTop",$("body").scrollTop()+25)})},listen:function(){var a=this;this.dom.find("button.finish").click(function(){a.dom.remove();c.dataStore.getFresh(a.model.key(),function(b){a.callback(b)})})},loadAllEditableFields:function(a){var b=this;c.dataStore.get("meta/"+
a.getType()+"::new",function(d){d.get("requirements",function(e){d.get("nonrequirements",function(f){$.each(e,function(g,h){b.addEditableField(h,a)});$.each(f,function(g,h){b.addEditableField(h,a)})})})})},addEditableField:function(a,b){var d=this.dom.children("div"),e=this;b.get(a.get("field"),function(f){if(f==""||f.match(/^[\s]+$/))f="n/a";if(a.get("editbox")!=0){if(a.get("type")=="textarea")d.append("<span>"+a.get("descript")+"</span> <p class='editable hoverable' rel='"+a.get("field")+"'>"+f+
"</p>");else if(a.get("type")=="input")d.append("<span>"+a.get("descript")+"</span> <strong class='editable clickable' rel='"+a.get("field")+"'>"+f+"</strong>");else if(a.get("type").indexOf("<")>=0){var g=a.get("type").match(/\<([A-Z][\w]+)\>/)[1];b.get(a.get("field"),function(h){e.addEntityChooser(a,h,g)})}a.get("field")==="lng"&&e.addEditableMap(d,b);a.get("field")}})},addEditableMap:function(a,b){var d=this;a.append($("<button/>",{text:"Open a map for editing the place...",click:function(){var e=
new c.PopoverMap(b,function(f,g){c.user.editor.mapProcess2(f,g,d.dom);delete e})}}))},addEntityChooser:function(a,b){var d=this;d.dom.children("div").append("<span>"+a.get("descript")+"</span>");c.IO.require("components/ListComponent",function(){var e=new c.ListComponent,f=$("<div/>",{"class":"ListComponent verysimple"});e.setSandbox(f);d.dom.children("div").append(f);e.initialize(c.dataStore.auxiliaryDataProvider(b))})}};c.PopoverMap=function(a,b){this.start(a,b)};c.PopoverMap.prototype={start:function(a,
b){c.IO.require("components/AMap2",function(){var d=google.maps,e=new d.LatLng(48,-0.3),f=3;if(a.get("lat")&&a.get("lng")){e=new d.LatLng(a.get("lat"),a.get("lng"));f=10}var g=$("<div/>",{"class":"edit_map",css:{height:$(window).height()-125}}),h=$("<a/>",{"class":"done",text:"Save new map position",href:"#"}),i=$("<img/>",{"class":"crosshairs",src:"/media/ui/crosshairs.png"}),k=$("<input/>",{"class":"geocode",value:"Search"}),j=$("<div/>",{"class":"popover",html:$("<div/>",{"class":"popover_map_panel",
html:g.after($("<div/>",{"class":"done",html:h.after($("<a/>",{href:"#",text:"Cancel",click:function(){j.remove();return false}})).after($("<span/>",{text:"Align the crosshairs over the target..."}))})).after(k).after(i)})});$("body").append(j);var m=c.Config.maps.getGoogleMapOptions();m.mapTypeId="hybrid";m.center=e;m.zoom=f;var n=new d.Map(g[0],m),o=[],l=undefined;h.bind("click",function(){b(n.getCenter().lat(),n.getCenter().lng());j.remove();return false});k.bind("keydown",function(){clearTimeout(l)}).bind("keyup",
function(){clearTimeout(l);var p=$(this);l=setTimeout(function(){(new d.Geocoder).geocode({address:p.attr("value")},function(q,r){if(r==="OK"){for(var s in o)o[s].setMap(null);var t=new d.LatLngBounds;for(s in q){o.push(new d.Marker({position:q[s].geometry.location,map:n,tile:"TD"}));t.extend(q[s].geometry.location)}n.fitBounds(t)}})},700)});e=$(window).height()-j.find(".popover_map_panel").height();j.css("padding-top",$("body").scrollTop()+e/2);i.css("left",g.width()/2-15).css("top",g.height()/2-
15)})}}})();
(function(){var c=Archmap;c.componentBuilder=function(a){var b=new c[a.component];b.setSandbox(a.sandbox);b.initialize(c.dataStore.auxiliaryDataProvider(a.provider));return b};c.defineComponent=function(a){var b=a.name;c[b]=function(d){this.inlineOptions={};this.___componentName=b;if(d!==undefined){var e=d.sandbox,f=d.provider;delete d.sandbox;delete d.provider;this.setOptions(d);if(e&&this.setSandbox){this.setSandbox(e);this.sandbox.addClass(b)}if(f&&this.initialize){f=f instanceof c.DataProvider?f:
c.dataStore.auxiliaryDataProvider(f);this.initialize(f)}}c.components.push(this)};c[b].prototype=a.extend?new c[a.extend]:{};jQuery.extend(c[b].prototype,a.methods||{})};c.newComponent=function(a){c.defineComponent(a)};c.GenericComponent=function(){};c.GenericComponent.prototype={addGenericListeners:function(){var a=this;$("html").bind("dataProviderReady",function(b,d){a.initialize(d)});$("html").bind("windowResized",function(){a.resize()})},resize:function(){return false},getModel:function(a){return this.dataProvider.dataStore.get(a)},
selectModel:function(a){if(_.isString(a)===false)a=a.key();this.dataProvider.select(a,this)},multiselectModel:function(a){this.dataProvider.multiselect(a,this)},unselectModel:function(a){this.dataProvider.unselect(a,this)},setSandbox:function(a){this.sandbox=a;return this},setOptions:function(a){this.inlineOptions=a||{}},loadTemplate:function(a,b){if(_.isFunction(a)){b=a;a=this.___componentName}var d=this;c.IO.getComponentHtml(a,function(e){d.sandbox.append(e);b.apply(d)})},destroy:function(){_.each(_.keys(this),
function(a){delete this[a]},this)}};c.SingletonComponent=function(){};c.SingletonComponent.prototype=new c.GenericComponent;jQuery.extend(c.SingletonComponent.prototype,{initialize:function(){this.addListeners();this.start()},start:function(){return false},boot:function(){},addListeners:function(){this.addGenericListeners()},request_and_wait:function(a,b){b=a.dataProvider.model.key()+"/"+b;var d=this;a.request(b,function(e,f){d.start();d.render(e,f)})},resize:function(){return false},clean:function(){$(this.dom).empty();
this.sandbox.empty()}});c.GroupComponent=function(){};c.GroupComponent.prototype=new c.GenericComponent;jQuery.extend(c.GroupComponent.prototype,{addListeners:function(){this.addGenericListeners();var a=this;$("html").bind("newDataProvider",function(b,d){a.unrender();a.boot(d);a.render()});$("html").bind("dataProviderRefreshed",function(b,d){if(d.model.key()===a.dataProvider.model.key()){a.unrender();a.boot(d);a.render()}});$.each({modelHoverOn:"hoverOnModel",modelHoverOff:"hoverOffModel",modelSelected:"highlightModel",
modelUnselected:"unhighlightModel",modelBlurred:"blurModel",modelFocused:"focusModel",modelSubfocused:"subfocusOnModel",modelUnsubfocused:"unsubfocusOnModel"},function(b,d){$("html").bind(b,function(e,f,g){try{a[d](f,g)}catch(h){a[d](f)}})})},initialize:function(a){this.boot(a);this.hangups=[];this.addListeners();this.start()},boot:function(a){this.dataProvider=a},start:function(){return false},prerender:function(){return false},render:function(){this.prerender();var a=this.dataProvider.model;a.key()!=
"catalog/collection"&&this.renderModel(a);this.finalize()},renderModel:function(){return false},unrender:function(){return false},rerender:function(){this.unrender();this.render()},blurFilter:function(a){this.blurChildren(this.dataProvider.model,a)},blurChildren:function(a,b){var d=this;a.iterateChildren(function(e,f){if(f.isExpandable())d.blurChildren(f,b);else b(f)?f.focus():f.blur()})},preventFinalize:function(){this.hangups.push(true)},enableFinalize:function(){this.hangups.pop();return this},
canBeFinalized:function(){if(this.hangups.length===0)return true},hoverModel:function(a){this.dataProvider.hover(a)},unhoverModel:function(a){this.dataProvider.unhover(a)},subfocusModel:function(a){this.dataProvider.subfocus(a)},unsubfocusModel:function(a){this.dataProvider.unsubfocus(a)},highlightModel:function(){return false},unhighlightModel:function(){return false},focusModel:function(){return false},blurModel:function(){return false},finalize:function(){return false},hoverOnModel:function(){return false},
hoverOffModel:function(){return false},subfocusOnModel:function(){return false},unsubfocusOnModel:function(){return false}})})();
(function(){Archmap.Config={abbrevs:{building:"b",buildings:"b",place:"pl",places:"pl",socialentity:"se",socialentities:"se",image:"i",images:"i",word:"w",words:"w",lexiconentry:"w",lexiconentries:"w"},markers:{shapes:{arrow:"M 5 10 L 14 10 12 8 12 12 14 10 12 8 14 10",arrowColor:"#89e",arrowHead:"M 14 10 L 12 8 12 12 14 10 12 8"},colors:{defaultIcon:"darkslateblue",iconHover:"yellow",iconHighlight:"firebrick"}},texts:{mapMarkerHoverTipText:"Click the marker to find out more. Double-click to visit the monograph.",
mapMultiMarkerHoverTipText:"Shift-click this church to compare it the others in the sidebar."},maps:{getGoogleMapOptions:function(){return{center:new google.maps.LatLng(48,2),zoom:6,mapTypeId:google.maps.MapTypeId.TERRAIN,mapTypeControl:false,navigationControl:false,disableDefaultUI:true}},googleMapStylers:{landscape:{visibility:"on",hue:"#00ff09"},water:{visibility:"simplified",hue:"#7700aa",lightness:100}},historicalMapCollection:"collection/182",zoomInButtonImage:"/media/ui/zoom_in_alt.png",zoomOutButtonImage:"/media/ui/zoom_out_alt.png",
zoomInButtonImageSmall:"/media/ui/zoom_in_small.png",zoomOutButtonImageSmall:"/media/ui/zoom_out_small.png"},hints:{}}})();
(function(){var c=Archmap;c.DataStore=function(a){this.initialize(a)};c.DataStore.prototype={initialize:function(a){this.user=a;this.data={};this.providers={};this.dataProvider=null;this.currentHash=window.location.hash;var b=this;$("html").bind("changeDataProvider",function(d,e){b.changeDataProvider(e)});$("html").bind("refreshDataProvider",function(d,e){b.refreshProvider(e)})},get:function(a,b,d){if(a===undefined)return false;a=a.toLowerCase();if(a===undefined||a=="")return false;var e=this.localGet(a);
if(d!==true&&e){_.isFunction(b)&&b(e);return e}else{this.remoteGet(a,b,d);return false}},localGet:function(a){return this.data[a]?this.data[a]:false},remoteGet:function(a,b,d){var e=this;c.IO.getJSONModel(a,function(f){f=f.archmap_says.model;if(_.isFunction(b))if(e.data[f])b(e.data[f]);else throw"AskedForItButDidntGetItError";},d)},getFresh:function(a,b){this.get(a,b,true)},getMetaForModelAndField:function(a,b,d){this.get("meta/"+a+"::"+b,d)},keyPush:function(a,b){this.data[a.toLowerCase()]=b},push:function(a){this.keyPush(a.key(),
a)},infuseInline:function(a,b){var d=this;this.convertJSONToArchObjects(a,function(e,f){f!==undefined?d.setDataProvider(f):d.setDataProvider(e);b()})},convertJSONToArchObjects:function(a,b){if(a.method!=="shortlist"&&a.system_model!=="search"){var d=this;this.get(a.model,function(f){if(typeof b==="function"){var g=d.recurseForModels(a.response,a.model,a.method);b(g,f)}})}else{var e=this.recurseForModels(a.response,a.model,a.method);typeof b==="function"&&b(e);return e}},recurseForModels:function(a,
b,d){var e=undefined;if(c.Utilities.isArray(a)){for(var f in a)if(typeof a[f]==="object"){var g=this.recurseForModels(a[f],b,d);try{a[f]=g.getReceipt()}catch(h){a[f]=g}}this.get(b).data[d]=a}else if(typeof a==="object")for(var i in a)if(typeof Archmap[i]==="function"){f=a[i].uri;e=g=new Archmap[i](a[i]);this.keyPush(f,g);if(f===b)this.recurseForModels(a[i],f,d);else if(b&&this.get(b)){this.get(b).data[d]=g.getReceipt();this.recurseForModels(a[i],g.key(),null)}else throw"NoRecordOfParentError";}else typeof a[i]===
"object"&&this.recurseForModels(a[i],b,i);else if(this.get(b))this.get(b).data[d]=a;if(e==undefined)e=a;return e},setDataProvider:function(a){this.dataProvider=new c.DataProvider(this.data[a.key()],this);this.providers[a.key()]=this.dataProvider;this.dataProvider.ready();c.State.save(a)},changeDataProvider:function(a){this.dataProvider=new c.DataProvider(a,this);$("html").trigger("newDataProvider",[this.dataProvider]);c.State.save(a)},auxiliaryDataProvider:function(a){if(a.key()in this.providers)return this.providers[a.key()];
this.providers[a.key()]=new c.DataProvider(a,this);return this.providers[a.key()]},refreshProvider:function(a){var b=this;a?this.getFresh(a,function(d){b.providers[a].model=d;$("html").trigger("dataProviderRefreshed",[b.providers[a]])}):this.getFresh(b.dataProvider.model.key(),function(d){b.changeDataProvider(d)})}};c.Receipt=function(a){this.key=a;this.name="Receipt for "+this.key};c.Receipt.prototype={checkout:function(){return c.dataStore.get(this.key)}};c.DataProvider=function(a,b){this.model=
a;this.id=this.model.get("id");this.dataStore=b;this.selection=[];this.subfocusedModel=undefined};c.DataProvider.prototype={ready:function(){$("html").trigger("dataProviderReady",this)},isDataProvider:function(){return true},key:function(){return this.model.key()},get:function(a){return this.model.get(a.toLowerCase())},select:function(a,b){if(this.isThisModelSelected(a))c.shiftOn===false?this.dataStore.get(a).visit():this.unselect(a,b);else{c.provider().isIterable()===false&&this.dataStore.get(a).visit();
this.subfocusedModel!==undefined&&this.unsubfocus();c.shiftOn===false&&this.clearSelection();this.multiselect(a,b)}},multiselect:function(a,b){this.selection.push(a);buffered_hash="";for(var d in this.selection)buffered_hash+="/"+this.selection[d];this.dataStore.get(a).select(b)},isThisModelSelected:function(a){for(var b in this.selection)if(this.selection[b]==a)return true;return false},clearSelection:function(){for(;this.selection.length>0;)this.dataStore.get(this.selection.pop()).unselect()},unselect:function(a){for(var b in this.selection)this.selection[b]==
a&&this.selection.splice(b,1);this.dataStore.get(a).unselect()},subfocus:function(a){this.clearSelection();this.subfocusedModel!==undefined&&this.subfocusedModel.unsubfocus();this.dataStore.get(a).subfocus();this.subfocusedModel=this.dataStore.get(a)},getSelectionStack:function(){return this.selection},unsubfocus:function(){this.subfocusedModel.unsubfocus();this.subfocusedModel=undefined},hover:function(a){for(var b in this.selection)if(this.selection[b]==a)return 0;this.dataStore.get(a).hover()},
unhover:function(a){for(var b in this.selection)if(this.selection[b]==a)return 0;this.dataStore.get(a).unhover()},refresh:function(){c.dataStore.refreshProvider(this.key())}}})();
(function(){var c=Archmap;c.Model=function(a){this.data=a};c.Model.prototype={initialize:function(a){this.data=a},key:function(){return this.get("uri")},get:function(a,b,d){if(this.data[a]!==undefined){var e=this.data[a];if(e instanceof c.Receipt)e=e.checkout();else if(c.Utilities.isArray(e)){var f=this.checkoutReceiptArray(e);if(f.length===0)f=e;e=f}if(typeof b=="function")b(e);else return e}else if(a in this.whitelist){var g=this;c.IO.getJSONModel(this.key()+"/"+a,function(h,i){if(typeof b==="function"){if(g.data[a]!==
i)g.data[a]=i;g.get(a,b)}},undefined,undefined,function(){d&&d()})}else return false},getFresh:function(a,b){var d=this;this.data[a]=undefined;c.IO.getJSONModel(this.key()+"/"+a,function(e,f){d.data[a]=f;d.get(a,b)},true)},getOriginalKey:function(){return this.key()},getAuthor:function(a){if(this.get("author_id"))return c.dataStore.get("person/"+this.get("author_id"),function(b){typeof a==="function"&&a(b)});return false},getType:function(){return this.type},getItem:function(){return false},getReceipt:function(){return new c.Receipt(this.get("uri"))},
checkoutReceiptArray:function(a){var b=[],d=0;for(d=0;d<a.length;d+=1)if(a[d]instanceof c.Receipt)b[d]=a[d].checkout();return b},shout:function(a,b){try{$("html").trigger(a,[this.key(),b])}catch(d){}},select:function(a){this.shout("modelSelected",a)},unselect:function(){this.shout("modelUnselected")},hover:function(){this.shout("modelHoverOn")},unhover:function(){this.shout("modelHoverOff")},focus:function(){this.shout("modelFocused")},blur:function(){this.shout("modelBlurred")},update:function(){this.shout("modelUpdated")},
subfocus:function(){this.shout("modelSubfocused")},unsubfocus:function(){this.shout("modelUnsubfocused")},visit:function(){window.location.href=c.uri+"/"+this.key()},set:function(a,b,d){this.put(a,b,d)},put:function(a,b,d){c.IO.put(this.key(),a,b,function(e){d!==undefined&&d(e)})},edit:function(a,b){new c.PopoverEditor(this,function(){a()},b)},isExpandable:function(){var a=c.dataStore.dataProvider.id;return this.type=="Collection"&&this.get("id")!==a?true:false},isIterable:function(){if(this instanceof
c.Collection||this instanceof c.Search)return true;if(this.getItem()&&this.getItem()instanceof c.Collection)return true;return false},isProvider:function(){return this.get("id")===c.dataStore.dataProvider.id?true:false},iterateChildren:function(a){this.get("members",function(b){try{$.each(b,function(e,f){a(e,f)})}catch(d){}})},iterateMembers:function(a,b,d){var e={};this.get("members",function(f){d===true&&f.reverse();$.each(f,function(g,h){e[h.key()]=a(g,h)});typeof b==="function"&&b()});return e},
mapMembers:function(){var a=_.map(this.get("members"),function(b){callback(b)});typeof finalizeCallback==="function"&&finalizeCallback();return a},toString:function(){return this.type+"\t"+this.get("id")},isOfType:function(a){if(this.type.toLowerCase()==a.toLowerCase())return true;return false},isanitem:function(){return false},whitelist:{descript:true,relations:true}};$.each(["Building","Person","Place","Publication","Catalog","Image","Node","Map","HistoricalEvent","LexiconEntry","SocialEntity",
"Note","Collection","Search","Slideshow","CollectionItem","Meta","Slide","BuildingModel","Keyword","ImageType"],function(a,b){c[b]=function(d){this.data=d;this.type=b};c[b].prototype=new c.Model(this.data)});$.each(["Story","Feature","SocialEntity","Chapter"],function(a,b){c[b]=function(d){this.data=d;this.type=b};c[b].prototype=new c.Collection(this.data)});jQuery.extend(c.Building.prototype,{get:function(a){var b={naveHeight:true,naveWidth:true,aisleHeight:true,aisleWidth:true};return this.buildingModel!==
undefined&&a in b?this.buildingModel[a]():c.Model.prototype.get.apply(this,arguments)},getBuildingModel:function(a){var b=this;this.get("model",function(d){a(d);b.buildingModel=d})},whitelist:{floorplan:true,frontispiece:true,nave:true,plan:true,elevation:true,history:true,chronology:true,significance:true,bibliography:true,model:true,images:true,canonicalSlideshow:true,bibliography_list:true,historical_events:true,relations:true,other_images:true,lat_section:true,exterior_chevet:true}});jQuery.extend(c.HistoricalEvent.prototype,
{whitelist:{buildings_involved:true,bibliography_list:true,descript:true,relations:true}});jQuery.extend(c.BuildingModel.prototype,{zones:{nave:1,transept:2,crossing:3,choir:4},positions:{main:1,arcade:2,aisle:3,wall:4,aisle2:5},dimensions:{apex:1,springer:2,boss:3,opening:4,wall:5,centerline:6},getDim:function(a,b,d){a=this.zones[a.toLowerCase()];b=this.positions[b.toLowerCase()];d=this.dimensions[d.toLowerCase()];return this.data.dimensions[a+"_"+b+"_"+d]},maxHeight:function(){return this.naveHeight()},
naveHeight:function(){return this.getDim("nave","main","apex")},naveWidth:function(){return this.getDim("nave","main","opening")},aisleHeight:function(){return this.getDim("nave","aisle","apex")},aisleWidth:function(){return this.getDim("nave","aisle","opening")}});jQuery.extend(c.Collection.prototype,{add:function(a,b,d,e){var f=this,g=this.last();g=g?g.get("sortval")+1:1;a={item_entity_id:a.type.toLowerCase(),item_id:a.get("id"),sortval:g};$.extend(a,e);c.IO.post(this.key(),a,function(){if(b){c.dataStore.get(f.key());
b===true?c.triggerEvent("refreshDataProvider"):c.triggerEvent("refreshDataProvider",[b])}typeof d==="function"&&d()})},whitelist:{members:true,render_style:true},last:function(){var a=this.get("members");return a?a[a.length-1]:false}});jQuery.extend(c.CollectionItem.prototype,{key:function(){if(this.getItem()instanceof c.Model)return this.getItem().key();return this.data.uri},get:function(a,b){var d=c.Model.prototype.get.apply(this,arguments);if(d===false||d===undefined)return this.getItem().get(a,
b);return d},isanitem:function(){return true},getOriginalKey:function(){return this.data.uri},getType:function(){return this.getItem().getType()},isOfType:function(a){return this.getItem().isOfType(a)},isExpandable:function(){return this.getItem().isExpandable()},getItem:function(){return this.get("item")},savePosition:function(a,b){c.IO.put("CollectionItem/"+this.data.id,"sortval",a,function(){typeof b==="function"&&b()})},del:function(a){c.IO.del(this.data.uri,function(){typeof a==="function"&&
a()})}});jQuery.extend(c.Meta.prototype,{whitelist:{requirements:true,nonrequirements:true}});jQuery.extend(c.Slide.prototype,{getImage:function(){return this.get("image")}});jQuery.extend(c.Person.prototype,{whitelist:{descript:true,relations:true,authored_books:true,edited_books:true,images:true,my_collections:true}});jQuery.extend(c.Publication.prototype,{whitelist:{descript:true,relations:true,authors:true,editors:true,buildings_referenced:true,events_referenced:true}});jQuery.extend(c.Image.prototype,
{whitelist:{plot:true,lexiconentries:true,imagetypes:true},get:function(a,b){if(a==="building")c.dataStore.get("building/"+this.get("building_id"),function(d){b(d)});else return c.Model.prototype.get.apply(this,arguments)},getImageArea:function(a,b){var d=this.maximizeForTile(a,b);return d.height*d.width},fitToSpace:function(a,b,d){a=this.maximizeForTile(a,b);b=a.width>a.height?this.maximizeForDimension(a.width):this.maximizeForDimension(a.height);b=this.get("medium").replace("/700/","/"+b+"/");d.height(a.height).width(a.width).attr("src",
b);return a},maximizeForTile:function(a,b){var d=a/b;return this.get("height")/this.get("width")>d?{height:a,width:this.get("width")*(a/this.get("height"))}:{width:b,height:this.get("height")*(b/this.get("width"))}},maximizeImg:function(a,b,d){a=this.maxSizeFor(a,b);d.attr("src",a[0]).width(a[1]).height(a[2])},isWidthwise:function(){if(this.get("width")>this.get("height"))return true;return false},centerAndFit:function(a,b,d,e,f){if(e!==undefined){e=this.fitToSpace(a-e.y,b-e.x,d);a=(a-e.height)/2}else{e=
this.fitToSpace(a,b,d);a=(a-e.height)/2}if(f===true){b=(b-e.width)/2;d.css("top",a).css("left",b)}else d.attr("image_id",this.get("id")).css("margin-top",a).css("margin-bottom",a)},centerAndScaleAndFit:function(a,b,d,e,f){f!==undefined?this.fitToSpace(a-f.y,b-f.x,d):this.fitToSpace(a,b,d);b=e/parseFloat(this.get("scale"));if(!isNaN(b)){d.width(d.width()*b).height(d.height()*b);d.attr("image_id",this.get("id")).css("margin-top",(a-d.height())/2)}},maximizeForDimension:function(a){return a>1700?2E3:
a>1300?1700:a>700?1300:a>300?700:a>100?300:a>50?100:50},urlForSize:function(a){return this.get("medium").replace("/700/","/"+a+"/")},scale:function(a,b){var d=b/parseFloat(this.get("scale"));isNaN(d)||a.width(a.width()*d).height(a.height()*d)},addKeyword:function(a){this.put("newKeyword",a)},removeKeyword:function(a){this.put("removeKeyword",a)}});c.BlankImage=function(){};c.BlankImage.prototype={get:function(a){return a in{thumbnail:true,small:true,medium:true}?"/media/ui/blank2.png":false},maximizeForTile:function(a,
b){return{height:a/2,width:b/2}},centerAndFit:function(){return false},maxHeight:function(){return false}};jQuery.extend(c.Map.prototype,{whitelist:{shape_collection:true}});jQuery.extend(c.Search.prototype,{iterateMembers:function(a,b){this.get("quicksearch",function(d){$.each(d,function(e,f){a(e,f)});typeof b==="function"&&b()})},whitelist:{nonrequirements:true,facetedimages:true}})})();
(function(){var c=Archmap;c.Elements={};c.Elements.UIStuff={closeButton:function(){return $("<img/>",{src:"/media/ui/close.png"})},arrow:function(a){return $("<img/>",{src:"/media/ui/"+a+"_arrow.png"})},upArrow:function(){return this.arrow("up")},downArrow:function(){return this.arrow("down")},helpPopoverLink:function(a){return $("<div/>",{"class":"helpPopoverLink",html:$("<img/>",{src:"/media/ui/helpPopover.png"}),click:function(b){$("div#container").append(c.Elements.UIStuff.helpPopover({html:a.html,
css:{right:$(window).width()-b.pageX-15,top:b.pageY-15},highlight:a.highlight}))}})},helpPopover:function(a){a.highlight!==undefined&&a.highlight.addClass("helpHighlight");var b=$("<div/>",{"class":"helpPopoverClose",html:$("<img/>",{src:"/media/ui/close.png"}),click:function(){a.highlight!==undefined&&a.highlight.removeClass("helpHighlight");$(this).parent().remove()}});return $("<div/>",{"class":"helpPopover "+a.extraClasses,css:a.css,html:$("<div/>",{"class":"padding",html:a.html})}).prepend(b)},
expandButton:function(a){var b=$("<img/>",{"class":"expand",src:"/media/ui/closed_arrow.png"});b.toggle(function(){$(this).attr("src","/media/ui/open_arrow.png");a.open()},function(){$(this).attr("src","/media/ui/closed_arrow.png");a.close()});a.trigger!==undefined&&a.trigger.click(function(){b.trigger("click")});return $("<strong/>",{"class":"expand",html:b})},expandableListItem:function(a){var b=$("<div/>",{"class":"visible"}).append(a.visible),d=$("<div/>",{"class":"hidden",css:{display:"none"}}).append(a.hidden),
e=$("<li/>",{"class":"expandable"}).append(b).append(d);b.prepend(c.Elements.UIStuff.expandButton({open:function(){e.find(".hidden").slideDown("fast");typeof a.open==="function"&&a.open()},close:function(){e.find(".hidden").slideUp("fast");typeof a.close==="function"&&a.close()},trigger:a.trigger}));return e},standardListItem:function(a){if(a.classes===undefined)a.classes="";if(a.linkClasses===undefined)a.linkClasses="";var b=$("<li/>",{data:{originalKey:a.originalKey,key:a.key},"class":"standard-list-item "+
a.classes,html:$("<a/>",{href:"/"+a.key,html:"<em>"+a.type+"</em> <span>"+a.name+"</span>","class":"standard-list-item-link "+a.linkClasses}),mouseover:function(){typeof a.mouseover==="function"&&a.mouseover()},mouseout:function(){typeof a.mouseout==="function"&&a.mouseout()}});a.click!==undefined&&b.find("a").click(function(){a.click(a.key);return false});return b},slideUpArrow:"",slideDownArrow:""};c.Elements.ScrollableDiv=function(a){this.initialize(a)};c.Elements.ScrollableDiv.prototype={initialize:function(a){var b=
a.appendTo;this.parent=b;var d=a.height||200,e=$("<div/>",{"class":"scrollable-nubbin"}),f=$("<div/>",{"class":"scrollable-scrollbar",css:{height:d},html:e}),g=$("<div/>",{"class":"scrollable-inside",css:{height:d},html:$("<div/>",{"class":"scrollable-contents",html:a.contents})}),h=$("<div/>",{"class":"scrollable-outside",css:{height:d},html:g});b.append(h).append(f);var i=undefined;g.mouseover(function(){e.addClass("hovering");i=setInterval(function(){var k=g.find(".scrollable-contents").height()/
h.height(),j=parseFloat(g.scrollTop());e.css("top",j/k)},10)}).mouseout(function(){e.removeClass("hovering");clearInterval(i)});c.IO.require("dependencies/DisableTextSelect",function(){var k=undefined,j=false;e.mousedown(function(m){if(j===false){b.disableTextSelect();k=m.pageY}j=true});$("html").mousemove(function(m){if(j){var n=m.pageY-k;if(n>=0){if(n>d-e.height())n=d-e.height();e.css("top",n);m=g.find(".scrollable-contents").height()/h.height();g.scrollTop(n*m)}else{c.log("---");c.log(d-e.height());
c.log(m.pageY);c.log(k)}}}).mouseup(function(){j=false;b.enableTextSelect()})});this.nubbin=e;this.scrollable=g;this.container=h;this.calculateNubbinHeight()},replaceHtmlWith:function(a){this.parent.find(".scrollable-contents").html(a);this.calculateNubbinHeight()},calculateNubbinHeight:function(){this.nubbin.css("display","block");var a=this.scrollable.find(".scrollable-contents").height(),b=this.container.height();this.nubbin.height(b/a*b-3);a<=b&&this.nubbin.css("display","none")}};c.Elements.DarkroomOverlay=
function(a){this.initialize(a)};c.Elements.DarkroomOverlay.prototype={};c.Elements.BiggableImage=function(a){this.initialize(a)};c.Elements.BiggableImage.prototype={initialize:function(a){this.image=a.image;this.attachTo=a.attachTo===undefined?$("body"):a.attachTo;this.build();this.listen()},build:function(){this.img=$("<img/>",{src:this.image.get("thumbnail")});this.img.data(this.image);this.link=$("<a/>",{html:this.img})},listen:function(){var a=this;this.link.click(function(){a.makeBig()})},getElement:function(){return this.link},
makeBig:function(){this.attachTo.append((new c.Elements.DarkroomOverlay({})).getElement())}};c.Elements.Dragger=function(a){this.initialize(a)};c.Elements.Dragger.prototype={initialize:function(a){this.dragBar=a.dragBar;this.dragFunction=a.dragFunction;this.dragging=false;this.listen()},listen:function(){var a=this;this.dragBar.mousedown(function(){a.dragging=true});$("html").mousemove(function(b){a.dragging===true&&a.dragFunction(b,a.dragBar)}).mouseup(function(){a.dragging=false})}}})();
String.prototype.contains=function(c){return this.indexOf(c)>=0};
_.mixin({keyMap:function(c,a,b){var d={};_.each(c,function(e,f){var g=a.call(b,e,f),h=_.bind(g.hasOwnProperty,g);h("key")&&h("value")?d[g.key]=g.value:h("k")&&h("v")?d[g.k]=g.v:d[f]=g});return d},keyZip:function(c,a){return _.keyMap(c,function(b,d){return{key:b,value:a[d]}})},curry:function(c){var a=Array.prototype.slice.call(arguments,1);return function(){return c.apply(window,a.concat(_.toArray(arguments)))}},$flatten:function(c){return _.foldr(c,function(a,b){return a?b.after(a):b},null)}});
(function(){Archmap.Utilities={isArray:function(c){return Object.prototype.toString.call(c)==="[object Array]"},deaccent:function(c){_.each([["\u00c9","E"],["\u00e9","e"],["\u00c1","A"],["\u00e1","a"],["\u00ea","e"],["\u00e8","e"],["\u00f4","o"],["\u00e2","a"],["\u00e7","c"],["\u00ee","i"],["\u00f9","u"],["\u00fb","u"],["\u00c2","A"],["\u00d4","O"]],function(a){c=c.replace(a[0],a[1])});return c}}})();
(function(){var c=Archmap;c.shiftOn=false;c.rightClicking=false;c.overlays=[];c.current_hash=window.location.hash.toString().replace("#","");var a=$("html");a.keydown(function(b){if(b.shiftKey)c.shiftOn=true});a.bind("contextmenu",function(){c.rightClicking=true});a.keyup(function(b){if(!b.shiftKey)c.shiftOn=false;c.rightClicking=false});setInterval(function(){var b=window.location.hash.toString().replace("#","");if(c.current_hash!==b)try{c.popOverlay().clean()}catch(d){c.log(d)}c.current_hash=b},
200);c.pushOverlay=function(b,d){c.overlays.push(b);c.current_hash=d;window.location.hash=d};c.popOverlay=function(){window.location.hash="/";c.current_hash="";return c.overlays.pop()};c.imageCache=[];c.preloadImage=function(b){var d=document.createElement("img");d.src=b;c.imageCache.push(d)}})();
(function(){Archmap.LayoutManager={fullscreen:function(c,a){var b=function(){$("#container").height($(window).height()).width($(window).width());var d=$("#container").height();if($("#header").length>0)d=d-$("#header").height()-27;if($.isArray(c)===false)c=[c];$.each(c,function(e,f){$(f).height(d)});typeof a==="function"&&a(d)};b();$(window).resize(function(){b()});return this},fullscreenLogo:function(){$("div#logo").css("left",12);return this},searchAdjustment:function(){if($(".overflap").length!==
0){var c=99-parseInt($(".overflap").width()/$(window).width()*100,10),a=parseInt(185/$(window).width()*100,10);if(a>c)c=a;$("#navigation").css("right",c+"%")}return this},hoverListeners:function(){$("#header a").each(function(){var c=$(this);c.attr("href")!=="/"&&location.pathname==c.attr("href")&&c.addClass("currentpage")});Archmap.IO.require("dependencies/HoverIntent",function(){$("a.top.login").toggle(function(){var c=$(this).parent().find("div.popover-panel");if(c.length>0){c=c.clone();var a=
$(this).offset().left;c.removeClass("popover-panel").addClass("poppedover-panel").css("display","none").css("top",45).css("left",a).fadeIn("fast");$("body").append(c);$(this).data("pop",c)}},function(){var c=$(this).data("pop");c&&!c.hasClass("beinghovered")&&c.fadeOut("fast",function(){$(this).remove()})});$("#logo a").hoverIntent({over:function(){var c=$("<div/>",{"class":"buttontip",text:$(this).attr("tip"),css:{left:$(this).offset().left}});$(this).data("tip",c);$("div#container").append(c);c.fadeIn()},
out:function(){$(this).data("tip").fadeOut(function(){$(this).remove()})},interval:200,timeout:150})});return this}}})();
(function(){var c=Archmap,a,b,d,e,f=$(window),g={clean:function(){e=false;a.fadeOut("fast",function(){b.empty();c.popOverlay()})}},h=function(o){return o.match(/[a-z]+\/\d{4,7}/)[0]},i=function(){var o=$("html");$("div#stage").delegate("a.biggable","mouseover",function(){o.trigger("imageHoverOn",this)}).delegate("a.biggable","mouseout",function(){o.trigger("imageHoverOn",this)}).delegate("a.biggable","click",function(){var l=$(this),p=h(l.attr("href")),q=l.closest(".slideshow-holder").attr("rel");
if(q)c.IO.require("components/SlideshowViewer",function(){var r=new c.SlideshowViewer;c.pushOverlay(r,"slideshow");r.boot(q,p.split("/")[1])});else l.hasClass("stereoscopic")?j(p,true):j(p);return false});$("a.fullscreen").live("click",function(){var l=$(this),p=l.find("img").data("image"),q=$("<div class='popin'/>").appendTo(l.parent());p?m(p,q):c.dataStore.get(h(l.attr("href")),function(r){m(r,q)});l.remove();return false});o.bind("windowResized",function(){e&&e()})},k=function(){d.click(function(){g.clean();
return false})},j=function(o,l){c.dataStore.get(o,function(p){if(p.isOfType("Node")){e=false;window.open("/scripts/panorama.php?path="+p.get("swf"),"360 degree node view",n({menubar:1,resizable:1,width:f.width(),height:f.height()+25}))}else{var q=$("<a/>",{"class":"fullscreen",href:"/"+p.key(),html:$("<img/>",{src:p.get("thumbnail"),data:{image:p}})});a.fadeIn("fast");e=function(){p.centerAndFit(f.height(),f.width()-100,q.find("img"))};e();b.empty().append(q).append($("<h5/>",{className:"click-to-zoom",
text:"Click the image to zoom in"})).append($("<a/>",{"class":"more-information",href:"/"+p.key(),text:"More Information"}));c.pushOverlay(g,o);l&&$("a.fullscreen").trigger("click")}})},m=function(o,l){l.css({width:f.width()-30,height:f.height()-30});c.IO.require("components/GImageViewer",function(){new c.GImageViewer({provider:o,sandbox:l,background:"clear"})});l.find(".imageviewer").addClass("clear")},n=function(o){return _.map(o,function(l,p){return p+"="+l}).join(",")};c.ImageOverlays={listenForImages:function(){c.IO.require("components/ImageComponent",
function(){a=$("#big_image_container");b=$("#big_image");d=a.find("a.image_close");i();k()})},popopenImageMap:function(o){window.open("/"+o.key()+"?mode=naked&view=zoom","image",n({menubar:1,resizable:1,width:f.width(),height:f.height()+25}))}}})();
(function(){var c=Archmap,a,b,d,e=function(h){h.delegate("a.inline","mouseover",function(i){var k=$(this).attr("href").slice(1);clearTimeout(b);a=setTimeout(_.curry(f,k,i),500)}).delegate("a.inline","mouseout",function(){clearTimeout(a);b=setTimeout(function(){d&&d.fadeOut()},500)})},f=function(h,i){var k=_.curry(g,h,i);d!==undefined?d.fadeOut("fast",k):k()},g=function(h,i){var k=function(j,m){d=$("<div/>",{"class":"interlocution",html:_.$flatten([$("<a/>",{text:j.get("name"),href:"/"+j.key()}),$("<img/>",
{src:m.get("thumbnail")})]),css:{top:i.pageY-50,left:i.pageX+50},mouseout:function(){var n=$(this);b=setTimeout(function(){n.fadeOut()},500)},mouseover:function(){clearTimeout(b)}}).appendTo($("body"))};c.dataStore.get(h,function(j){j.get("frontispiece",function(m){k(j,m)},function(){k(j,"")})})};c.interlocute=function(h){e(h)}})();
